version: "3.7"

services:
  web-api:
    image: "docker.io/library/api_cegeka"
    container_name: web-api
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  app_data:
